/*
 * CIV UNIT OBJECT
 */
 
 // TO DO:
 //   ADD collateral immune
 //   CHANGE .promotions to use the .setPromotion{} function
 
 //   Naval Units
 //   Air Units
 
var UnitListing = new Array();
UnitListing.push("Lion");
UnitListing.push("Bear");
UnitListing.push("Panther");
UnitListing.push("Wolf");
UnitListing.push("Settler");
UnitListing.push("Worker");
UnitListing.push("Scout");
UnitListing.push("Explorer");
UnitListing.push("Warrior");
UnitListing.push("Quechua");
UnitListing.push("Swordsman");
UnitListing.push("Jaguar");
UnitListing.push("Gallic Warrior");
UnitListing.push("Praetorian");
UnitListing.push("Axeman");
UnitListing.push("Phalanx");
UnitListing.push("Vulture");
UnitListing.push("Dog Soldier");
UnitListing.push("Maceman");
UnitListing.push("Samurai");
UnitListing.push("Berserker");
UnitListing.push("Spearman");
UnitListing.push("Impi");
UnitListing.push("Holkan");
UnitListing.push("Pikeman");
UnitListing.push("Landskencht");
UnitListing.push("Musketman");
UnitListing.push("Musketeer");
UnitListing.push("Janissary");
UnitListing.push("Oromo Warrior");
UnitListing.push("Rifleman");
UnitListing.push("Redcoat");
UnitListing.push("Grenadier");
UnitListing.push("Anti-Tank Infantry");
UnitListing.push("Infantry");
UnitListing.push("SAM Infantry");
UnitListing.push("Mobile SAM");
UnitListing.push("Marine");
UnitListing.push("Navy Seal");
UnitListing.push("Paratrooper");
UnitListing.push("Mechanized Infantry");
UnitListing.push("Archer");
UnitListing.push("Skirmisher");
UnitListing.push("Bowman");
UnitListing.push("Longbowman");
UnitListing.push("Crossbowman");
UnitListing.push("Cho-Ko-Nu");
UnitListing.push("Chariot");
UnitListing.push("War Chariot");
UnitListing.push("Immortal");
UnitListing.push("Horse Archer");
UnitListing.push("Numidian Mercenary");
UnitListing.push("Keshik");
UnitListing.push("Knight");
UnitListing.push("Camel Archer");
UnitListing.push("Cataphract");
UnitListing.push("Conquistador");
UnitListing.push("Cuirassier");
UnitListing.push("Cavalry");
UnitListing.push("Cossack");
UnitListing.push("War Elephant");
UnitListing.push("Ballista Elephant");
UnitListing.push("Tank");
UnitListing.push("Panzer");
UnitListing.push("Modern Armor");
UnitListing.push("Gunship");
UnitListing.push("Catapult");
UnitListing.push("Hwacha");
UnitListing.push("Trebuchet");
UnitListing.push("Cannon");
UnitListing.push("Machine Gun");
UnitListing.push("Artillery");
UnitListing.push("Mobile Artillery");

function civUnit() {

  this.hp = 100;
  this.xp = 0;
  this.promotions = {
    'Accuracy': 0,       'Ace': 0,          'Ambush': 0,        'Amphibious': 0,  'Barrage': 0,  'Blitz': 0,  'Charge': 0,
    'City Garrison': 0,  'City Raider': 0,  'Combat': 0,        'Commando': 0,    'Cover': 0,    'Drill': 0,  'Flanking': 0,
    'Formation': 0,      'Guerilla': 0,     'Interception': 0,  'Leadership': 0,  'March': 0,    'Medic': 0,  'Mobility': 0,
    'Morale': 0,         'Navigation': 0,   'Pinch': 0,         'Range': 0,       'Sentry': 0,   'Shock': 0,  'Tactics': 0,
    'Woodsman': 0
  };

  // VALUES FROM XML FILE
  this.unitName = "";
  this.unitClass = "";
  this.combat = "";
  this.domain = "";
  this.bFirstStrikeImmune = 0;
  this.bNoDefensiveBonus = 0;
  this.bIgnoreBuildingDefense = 0;
  this.bNukeImmune = 0;
  this.flankingStrikes = {};
  this.iCost = 0;
  this.iCombat = 0;
  this.iAirCombat = 0;
  this.iFirstStrikes = 0;
  this.iChanceFirstStrikes = 0;
  this.iInterceptionProbability = 0;
  this.iEvasionProbability = 0;
  this.iWithdrawalProb = 0;
  this.iCollateralDamage = 0;
  this.iCollateralDamageLimit = 0;
  this.iCollateralDamageMaxUnits = 0;
  this.iCityAttack = 0;
  this.iCityDefense = 0;
  this.iAnimalCombat = 0;
  this.iHillsAttack = 0;
  this.iHillsDefense = 0;
  this.unitCombatAtkMods = {};
  this.unitCombatDfnMods = {};

  this.setPromotion = function(promo, setting) {
    this.promotions[promo] = setting;
  };
  
  this.removePromotion = function(promo) {
    this.promotions[promo] = 0;
  };
  
  this.clearPromotions = function() {
    for (var i = 0; i < this.promotions.length; i++) {
      this.promotions[i] = 0;
    }
  }
  
  this.setHP = function(hpValue) {
    this.hp = hpValue;
  };
  
  this.setUnitValues = function(unitTemplate) {
    switch (unitTemplate) {
      case "Lion":
        this.unitName = "Lion";
        this.unitClass = "LION";
        this.combat = "ANIMAL";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = -1;
        this.iCombat = 2;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        break;
      case "Bear":
        this.unitName = "Bear";
        this.unitClass = "BEAR";
        this.combat = "ANIMAL";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = -1;
        this.iCombat = 3;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        break;
      case "Panther":
        this.unitName = "Panther";
        this.unitClass = "PANTHER";
        this.combat = "ANIMAL";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = -1;
        this.iCombat = 2;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        break;
      case "Wolf":
        this.unitName = "Wolf";
        this.unitClass = "WOLF";
        this.combat = "ANIMAL";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = -1;
        this.iCombat = 1;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        break;
      case "Settler":
        this.unitName = "Settler";
        this.unitClass = "SETTLER";
        this.combat = "NONE";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 100;
        this.iCombat = 0;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        break;
      case "Worker":
        this.unitName = "Worker";
        this.unitClass = "WORKER";
        this.combat = "NONE"
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 60;
        this.iCombat = 0;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        break;
      case "Scout":
        this.unitName = "Scout";
        this.unitClass = "SCOUT";
        this.combat = "RECON";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 15;
        this.iCombat = 1;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 100;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        break;
      case "Explorer":
        this.unitName = "Explorer";
        this.unitClass = "EXPLORER";
        this.combat = "RECON";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 40;
        this.iCombat = 4;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        this.setPromotion('Guerilla', 1);
        this.setPromotion('Woodsman', 1);
        break;
      case "Warrior":
        this.unitName = "Warrior";
        this.unitClass = "WARRIOR";
        this.combat = "MELEE";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 15;
        this.iCombat = 2;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 25;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        break;
      case "Quechua":
        this.unitName = "Quechua";
        this.unitClass = "WARRIOR";
        this.combat = "MELEE";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 15;
        this.iCombat = 2;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 25;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"RANGED":100};
        this.unitCombatDfnMods = {"RANGED":100};
        this.clearPromotions();
        this.setPromotion('Combat', 1);
        break;
      case "Swordsman":
        this.unitName = "Swordsman";
        this.unitClass = "SWORDSMAN";
        this.combat = "MELEE";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 40;
        this.iCombat = 6;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 10;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        break;
      case "Jaguar":
        this.unitName = "Jaguar";
        this.unitClass = "SWORDSMAN";
        this.combat = "MELEE";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 35;
        this.iCombat = 5;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 10;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        this.setPromotion('Woodsman', 1);
        break;
      case "Gallic Warrior":
        this.unitName = "Gallic Warrior";
        this.unitClass = "SWORDSMAN";
        this.combat = "MELEE";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 40;
        this.iCombat = 6;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 10;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        this.setPromotion('Guerilla', 1);
        break;
      case "Praetorian":
        this.unitName = "Praetorian";
        this.unitClass = "SWORDSMAN";
        this.combat = "MELEE";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 45;
        this.iCombat = 8;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        break;
      case "Axeman":
        this.unitName = "Axeman";
        this.unitClass = "AXEMAN";
        this.combat = "MELEE";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 35;
        this.iCombat = 5;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"MELEE":50};
        this.unitCombatDfnMods = {"MELEE":50};
        this.clearPromotions();
        break;
      case "Phalanx":
        this.unitName = "Phalanx";
        this.unitClass = "AXEMAN";
        this.combat = "MELEE";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 35;
        this.iCombat = 5;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"MELEE":50};
        this.unitCombatDfnMods = {"CHARIOT":100, "MELEE":50};
        this.clearPromotions();
        break;
      case "Vulture":
        this.unitName = "Vulture";
        this.unitClass = "AXEMAN";
        this.combat = "MELEE";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 35;
        this.iCombat = 6;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"MELEE":25};
        this.unitCombatDfnMods = {"MELEE":25};
        this.clearPromotions();
        break;
      case "Dog Soldier":
        this.unitName = "Dog Soldier";
        this.unitClass = "AXEMAN";
        this.combat = "MELEE";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 35;
        this.iCombat = 4;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits =
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"MELEE":100};
        this.unitCombatDfnMods = {"MELEE":100};
        this.clearPromotions();
        break;
      case "Maceman":
        this.unitName = "Maceman";
        this.unitClass = "MACEMAN";
        this.combat = "MELEE";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 70;
        this.iCombat = 8;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"MELEE":50};
        this.unitCombatDfnMods = {"MELEE":50};
        this.clearPromotions();
        break;
      case "Samurai":
        this.unitName = "Samurai";
        this.unitClass = "MACEMAN";
        this.combat = "MELEE";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 70;
        this.iCombat = 8;
        this.iAirCombat = 0;
        this.iFirstStrikes = 2;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"MELEE":50};
        this.unitCombatDfnMods = {"MELEE":50};
        this.clearPromotions();
        this.setPromotion('Drill', 1);
        break;
      case "Berserker":
        this.unitName = "Berserker";
        this.unitClass = "MACEMAN";
        this.combat = "MELEE";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 70;
        this.iCombat = 8;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0; 
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 10;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"MELEE":50};
        this.unitCombatDfnMods = {"MELEE":50};
        this.clearPromotions();
        this.setPromotion('Amphibious', 1);
        break;
      case "Spearman":
        this.unitName = "Spearman";
        this.unitClass = "SPEARMAN";
        this.combat = "MELEE";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 35;
        this.iCombat = 4;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"MOUNTED":100};
        this.unitCombatDfnMods = {"MOUNTED":100};
        this.clearPromotions();
        break;
      case "Impi":
        this.unitName = "Impi";
        this.unitClass = "SPEARMAN";
        this.combat = "MELEE";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 35;
        this.iCombat = 4;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"MOUNTED":100};
        this.unitCombatDfnMods = {"MOUNTED":100};
        this.clearPromotions();
        this.setPromotion('Mobility', 1);
        break;
      case "Holkan":
        this.unitName = "Holkan";
        this.unitClass = "SPEARMAN";
        this.combat = "MELEE";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 1;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 35;
        this.iCombat = 4;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"MOUNTED":100};
        this.unitCombatDfnMods = {"MOUNTED":100};
        this.clearPromotions();
        break;
      case "Pikeman":
        this.unitName = "Pikeman";
        this.unitClass = "PIKEMAN";
        this.combat = "MELEE";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 60;
        this.iCombat = 6;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"MOUNTED":100};
        this.unitCombatDfnMods = {"MOUNTED":100};
        this.clearPromotions();
        break;
      case "Landsknecht":
        this.unitName = "Landsknecht";
        this.unitClass = "PIEKMAN";
        this.combat = "MELEE";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 60;
        this.iCombat = 6;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"MELEE":100, "MOUNTED":100};
        this.unitCombatDfnMods = {"MELEE":100, "MOUNTED":100};
        this.clearPromotions();
        break;
      case "Musketman":
        this.unitName = "Musketman";
        this.unitClass = "MUSKETMAN";
        this.combat = "GUNPOWDER";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 80;
        this.iCombat = 9;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        break;
      case "Musketeer":
        this.unitName = "Musketeer";
        this.unitClass = "MUSKETMAN";
        this.combat = "GUNPOWDER";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 80;
        this.iCombat = 9;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        break;
      case "Janissary":
        this.unitName = "Janissary";
        this.unitClass = "MUSKETMAN";
        this.combat = "GUNPOWDER";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 80;
        this.iCombat = 9;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"MELEE": 25, "MOUNTED": 25, "RANGED": 25};
        this.unitCombatDfnMods = {"MELEE": 25, "MOUNTED": 25, "RANGED": 25};
        this.clearPromotions();
        break;
      case "Oromo Warrior":
        this.unitName = "Oromo Warrior";
        this.unitClass = "MUSKETMAN";
        this.combat = "GUNPOWDER";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 1;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 80;
        this.iCombat = 9;
        this.iAirCombat = 0;
        this.iFirstStrikes = 1;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        this.setPromotion('Drill', 2);
        break;
      case "Rifleman":
        this.unitName = "Rifleman";
        this.unitClass = "RIFLEMAN";
        this.combat = "GUNPOWDER";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 110;
        this.iCombat = 14;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"MOUNTED": 25};
        this.unitCombatDfnMods = {"MOUNTED": 25};
        this.clearPromotions();
        break;
      case "Redcoat":
        this.unitName = "Redcoat";
        this.unitClass = "RIFLEMAN";
        this.combat = "GUNPOWDER";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 110;
        this.iCombat = 14;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"GUNPOWDER": 25, "MOUNTED": 25};
        this.unitCombatDfnMods = {"GUNPOWDER": 25, "MOUNTED": 25};
        this.clearPromotions();
        break;
      case "Grenadier":
        this.unitName = "Grenadier";
        this.unitClass = "GRENADIER";
        this.combat = "GUNPOWDER";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 100;
        this.iCombat = 12;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"RIFLEMAN": 50};
        this.unitCombatDfnMods = {"RIFLEMAN": 50};
        this.clearPromotions();
        break;
      case "Anti-Tank Infantry":
        this.unitName = "Anti-Tank Infantry"
        this.unitClass = "AT_INFANTRY";
        this.combat = "GUNPOWDER";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 120;
        this.iCombat = 14;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 20;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"ARMOR": 100};
        this.unitCombatDfnMods = {"ARMOR": 100};
        this.clearPromotions();
        this.setPromotion('Ambush', 1);
        break;
      case "Infantry":
        this.unitName = "Infantry";
        this.unitClass = "INFANTRY";
        this.combat = "GUNPOWDER";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 140;
        this.iCombat = 20;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"GUNPOWDER": 25};
        this.unitCombatDfnMods = {"GUNPOWDER": 25};
        this.clearPromotions();
        break;
      case "SAM Infantry":
        this.unitName = "SAM Infantry"
        this.unitClass = "SAM_INFANTRY";
        this.combat = "GUNPOWDER";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 150;
        this.iCombat = 18;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 40;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"HELICOPTER": 75};
        this.unitCombatDfnMods = {"HELICOPTER": 75};
        this.clearPromotions();
        break;
      case "Mobile SAM":
        this.unitName = "Mobile SAM";
        this.unitClass = "MOBILE_SAM";
        this.combat = "GUNPOWDER";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 220;
        this.iCombat = 22;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 50;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"HELICOPTER": 50};
        this.unitCombatDfnMods = {"HELICOPTER": 50};
        this.clearPromotions();
        break;
      case "Marine":
        this.unitName = "MARINE";
        this.unitClass = "RIFLEMAN";
        this.combat = "GUNPOWDER";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 160;
        this.iCombat = 24;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"ARTILLERY": 50, "MACHINE_GUN": 50};
        this.unitCombatDfnMods = {"ARTILLERY": 50, "MACHINE_GUN": 50};
        this.clearPromotions();
        this.setPromotion('Amphibious', 1);
        break;
      case "Navy Seal":
        this.unitName = "Navy Seal"
        this.unitClass = "MARINE";
        this.combat = "GUNPOWDER";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 160;
        this.iCombat = 24;
        this.iAirCombat = 0;
        this.iFirstStrikes = 1;
        this.iChanceFirstStrikes = 1;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"ARTILLERY": 50, "MACHINE_GUN": 50};
        this.unitCombatDfnMods = {"ARTILLERY": 50, "MACHINE_GUN": 50};
        this.clearPromotions();
        this.setPromotion('Amphibious', 1);
        this.setPromotion('March', 1);
        break;
      case "Paratrooper":
        this.unitName = "Paratrooper";
        this.unitClass = "PARATROOPER";
        this.combat = "GUNPOWDER";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 160;
        this.iCombat = 24;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 25;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        break;
      case "Mechanized Infantry":
        this.unitName = "Mechanized Infantry";
        this.unitClass = "MECHANIZED_INFANTRY";
        this.combat = "GUNPOWDER";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 200;
        this.iCombat = 32;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 20;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        this.setPromotion('March', 1);
        break;
      case "Archer":
        this.unitName = "Archer";
        this.unitClass = "ARCHER";
        this.combat = "RANGED";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus =0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 25;
        this.iCombat = 3;
        this.iAirCombat = 0;
        this.iFirstStrikes = 1;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 50;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 25;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        break;
      case "Skirmisher":
        this.unitName = "Skirmisher";
        this.unitClass = "ARCHER";
        this.combat = "RANGED";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 25;
        this.iCombat = 4;
        this.iAirCombat = 0;
        this.iFirstStrikes = 1;
        this.iChanceFirstStrikes = 1;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 50;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 25;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        break;
      case "Bowman":
        this.unitName = "Bowman";
        this.unitClass = "ARCHER";
        this.combat = "RANGED";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 25;
        this.iCombat = 3;
        this.iAirCombat = 0;
        this.iFirstStrikes = 1;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 50;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 25;
        this.unitCombatAtkMods = {"MELEE": 50};
        this.unitCombatDfnMods = {"MELEE": 50};
        this.clearPromotions();
        break;
      case "Longbowman":
        this.unitName = "Longbowman";
        this.unitClass = "LONGBOWMAN";
        this.combat = "RANGED";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 50;
        this.iCombat = 6;
        this.iAirCombat = 0;
        this.iFirstStrikes = 1;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 25;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 25;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        break;
      case "Crossbowman":
        this.unitName = "Crossbowman";
        this.unitClass = "CROSSBOWMAN";
        this.combat = "RANGED";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 60;
        this.iCombat = 6;
        this.iAirCombat = 0;
        this.iFirstStrikes = 1;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"MELEE": 50};
        this.unitCombatDfnMods = {"MELEE": 50};
        this.clearPromotions();
        break;
      case "Cho-Ko-Nu":
        this.unitName = "Cho-Ko-Nu"
        this.unitClass = "CROSSBOWMAN";
        this.combat = "RANGED";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 60;
        this.iCombat = 6;
        this.iAirCombat = 0;
        this.iFirstStrikes = 2;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 50;
        this.iCollateralDamageLimit = 60;
        this.iCollateralDamageMaxUnits = 5;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"MELEE": 50};
        this.unitCombatDfnMods = {"MELEE": 50};
        this.clearPromotions();
        break;
      case "Chariot":
        this.unitName = "Chariot";
        this.unitClass = "CHARIOT";
        this.combat = "MOUNTED";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 30;
        this.iCombat = 4;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 10;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"AXEMAN": 100};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        break;
      case "War Chariot":
        this.unitName = "War Chariot";
        this.unitClass = "CHARIOT";
        this.combat = "MOUNTED";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 1;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 30;
        this.iCombat = 5;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 10;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"AXEMAN": 100};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        break;
      case "Immortal":
        this.unitName = "Immortal";
        this.unitClass = "CHARIOT";
        this.combat = "MOUNTED";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 30;
        this.iCombat = 4;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 10;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"ARCHER": 50, "AXEMAN": 100};
        this.unitCombatDfnMods = {"ARCHER": 50};
        this.clearPromotions();
        break;
      case "Horse Archer":
        this.unitName = "Horse Archer";
        this.unitClass = "HORSE_ARCHER";
        this.combat = "MOUNTED";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 1;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {"CATAPULT":100, "TREBUCHET":100};
        this.iCost = 50;
        this.iCombat = 6;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 20;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 100;
        this.iCollateralDamageMaxUnits = 6;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"CATAPULT": 50};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        break;
      case "Numidian Mercenary":
        this.unitName =  "Numidian Mercenary";
        this.unitClass = "HORSE_ARCHER";
        this.combat = "MOUNTED";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 1;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {"CATAPULT":100, "TREBUCHET":100};
        this.iCost = 50;
        this.iCombat = 5;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 20;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 100;
        this.iCollateralDamageMaxUnits = 6;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"CATAPULT": 50, "MELEE": 50};
        this.unitCombatDfnMods = {"MELEE": 50};
        this.clearPromotions();
        this.setPromotion('Flanking', 1);
        break;
      case "Keshik":
        this.unitName = "Keshik";
        this.unitClass = "HORSE_ARCHER";
        this.combat = "MOUNTED";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {"CATAPULT":100, "TREBUCHET":100};
        this.iCost = 50;
        this.iCombat = 6;
        this.iAirCombat = 0;
        this.iFirstStrikes = 1;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 20;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 100;
        this.iCollateralDamageMaxUnits = 6;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"CATAPULT": 50};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        break;
      case "Knight":
        this.unitName = "Knight";
        this.unitClass = "KNIGHT";
        this.combat = "MOUNTED";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 1;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {"CATAPULT":100, "TREBUCHET":100};
        this.iCost = 90;
        this.iCombat = 10;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 100;
        this.iCollateralDamageMaxUnits = 6;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        break;
      case "Camel Archer":
        this.unitName = "Camel Archer";
        this.unitClass = "KNIGHT";
        this.combat = "MOUNTED";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 1;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {"CATAPULT":100, "TREBUCHET":100};
        this.iCost = 90;
        this.iCombat = 10;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 15;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 100;
        this.iCollateralDamageMaxUnits = 6;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        break;
      case "Cataphract":
        this.unitName = "Cataphract";
        this.unitClass = "KNIGHT";
        this.combat = "MOUNTED";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {"CATAPULT":100, "TREBUCHET":100};
        this.iCost = 90;
        this.iCombat = 12;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 100;
        this.iCollateralDamageMaxUnits = 6;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        break;
      case "Conquistador":
        this.unitName = "Conquistador";
        this.unitClass = "CUIRASSIER";
        this.combat = "MOUNTED";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 1;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.flankingStrikes = {"CATAPULT":100, "TREBUCHET":100, "CANNON":100};
        this.iCost = 100;
        this.iCombat = 12;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 15;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 100;
        this.iCollateralDamageMaxUnits = 6;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"MELEE": 50};
        this.unitCombatDfnMods = {"MELEE": 50};
        this.clearPromotions();
        break;
      case "Cuirassier":
        this.unitName = "Cuirassier";
        this.unitClass = "CUIRASSIER";
        this.combat = "MOUNTED";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 1;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.flankingStrikes = {"CATAPULT":100, "TREBUCHET":100, "CANNON":100};
        this.iCost = 100;
        this.iCombat = 12;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 15;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 100;
        this.iCollateralDamageMaxUnits = 6;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        break;
      case "Cavalry":
        this.unitName = "Cavalry";
        this.unitClass = "CAVALRY";
        this.combat = "MOUNTED";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.flankingStrikes = {"CATAPULT":100, "TREBUCHET":100, "CANNON":100};
        this.iCost = 120;
        this.iCombat = 15;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 30;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 100;
        this.iCollateralDamageMaxUnits = 7;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"CANNON": 50};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        break;
      case "Cossack":
        this.unitName = "Cossack";
        this.unitClass = "CAVALRY";
        this.combat = "MOUNTED";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.flankingStrikes = {"CATAPULT":100, "TREBUCHET":100, "CANNON":100};
        this.iCost = 120;
        this.iCombat = 15;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 30;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 100;
        this.iCollateralDamageMaxUnits = 7;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"CANNON": 50, "MOUNTED": 50};
        this.unitCombatDfnMods = {"MOUNTED": 50};
        this.clearPromotions();
        break;
      case "War Elephant":
        this.unitName = "War Elephant";
        this.unitClass = "WAR_ELEPHANT";
        this.combat = "MOUNTED";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 60;
        this.iCombat = 8;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"MOUNTED": 50};
        this.unitCombatDfnMods = {"MOUNTED": 50};
        this.clearPromotions();
        break;
      case "Ballista Elephant":
        this.unitName = "Ballista Elephant";
        this.unitClass = "WAR_ELEPHANT";
        this.combat = "MOUNTED";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 60;
        this.iCombat = 8;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"MOUNTED":50};
        this.unitCombatDfnMods = {"MOUNTED":50};
        this.clearPromotions();
        break;
      case "Tank":
        this.unitName = "Tank";
        this.unitClass = "TANK";
        this.combat = "ARMOR";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 180;
        this.iCombat = 28;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 60;
        this.iCollateralDamageMaxUnits = 5;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        this.setPromotion('Blitz', 1);
        break;
      case "Panzer":
        this.unitName = "Panzer";
        this.unitClass = "TANK";
        this.combat = "ARMOR";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 180;
        this.iCombat = 28;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 60;
        this.iCollateralDamageMaxUnits = 5;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"ARMOR":50};
        this.unitCombatDfnMods = {"ARMOR":50};
        this.clearPromotions();
        this.setPromotion('Blitz', 1);
        break;
      case "Modern Armor":
        this.unitName = "Modern Armor";
        this.unitClass = "MODERN_ARMOR";
        this.combat = "ARMOR";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 240;
        this.iCombat = 40;
        this.iAirCombat = 0;
        this.iFirstStrikes = 1;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 60;
        this.iCollateralDamageMaxUnits = 6;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        this.setPromotion('Blitz', 1);
        break;
      case "Gunship":
        this.unitName = "Gunship";
        this.unitClass = "GUNSHIP";
        this.combat = "HELICOPTER";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.flankingStrikes = {"CANNON":100, "ARTILLERY":100, "MOBILE_ARTILLERY":100};
        this.iCost = 160;
        this.iCombat = 24;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 25;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 100;
        this.iCollateralDamageMaxUnits = 8;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"ARMOR":100};
        this.unitCombatDfnMods = {"ARMOR":100};
        this.clearPromotions();
        break;
      case "Catapult":
        this.unitName = "Catapult";
        this.unitClass = "CATAPULT";
        this.combat = "SEIGE";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 50;
        this.iCombat = 5;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 100;
        this.iCollateralDamageLimit = 50;
        this.iCollateralDamageMaxUnits = 6;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        break;
      case "Hwacha":
        this.unitName = "Hwacha";
        this.unitClass = "CATAPULT";
        this.combat = "SIEGE";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 50;
        this.iCombat = 5;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 100;
        this.iCollateralDamageLimit = 50;
        this.iCollateralDamageMaxUnits = 6;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"MELEE":50};
        this.unitCombatDfnMods = {"MELEE":50};
        this.clearPromotions();
        break;
      case "Trebuchet":
        this.unitName = "Trebuchet";
        this.unitClass = "TREBUCHET";
        this.combat = "SIEGE";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 80;
        this.iCombat = 4;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 100;
        this.iCollateralDamageLimit = 50;
        this.iCollateralDamageMaxUnits = 6;
        this.iCityAttack = 100;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        break;
      case "Cannon":
        this.unitName = "Cannon";
        this.unitClass = "CANNON";
        this.combat = "SIEGE";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 100;
        this.iCombat = 12;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 100;
        this.iCollateralDamageLimit = 60;
        this.iCollateralDamageMaxUnits = 7;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {};
        this.unitCombatDfnMods = {};
        this.clearPromotions();
        break;
      case "Machine Gun":
        this.unitName = "Machine Gun";
        this.unitClass = "MACHINE_GUN";
        this.combat = "SEIGE";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 125;
        this.iCombat = 18;
        this.iAirCombat = 0;
        this.iFirstStrikes = 1;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 20;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 100;
        this.iCollateralDamageLimit = 50;
        this.iCollateralDamageMaxUnits = 6;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"GUNPOWDER":50};
        this.unitCombatDfnMods = {"GUNPOWDER":50};
        this.clearPromotions();
        break;
      case "Artillery":
        this.unitName = "Artillery";
        this.unitClass = "ARTILLERY";
        this.combat = "SIEGE";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 150;
        this.iCombat = 18;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 100;
        this.iCollateralDamageLimit = 70;
        this.iCollateralDamageMaxUnits = 8;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"SIEGE":50};
        this.unitCombatDfnMods = {"SIEGE":50};
        this.clearPromotions();
        break;
      case "Mobile Artillery":
        this.unitName = "Mobile Artillery";
        this.unitClass = "MOBILE_ARTILLERY";
        this.combat = "SIEGE";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.flankingStrikes = {};
        this.iCost = 200;
        this.iCombat = 26;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 100;
        this.iCollateralDamageLimit = 70;
        this.iCollateralDamageMaxUnits = 8;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatAtkMods = {"SIEGE":50};
        this.unitCombatDfnMods = {"SIEGE":50};
        this.clearPromotions();
        break;
    }
  
  };
  
  
}
