/*
 * CIV UNIT OBJECT
 */

function civUnit() {

  this.hp = 100;
  this.xp = 0;
  this.promotions = {
    'Accuracy': 0,       'Ace': 0,          'Ambush': 0,        'Amphibious': 0,  'Barrage': 0,  'Blitz': 0,  'Charge': 0,
    'City Garrison': 0,  'City Raider': 0,  'Combat': 0,        'Commando': 0,    'Cover': 0,    'Drill': 0,  'Flanking': 0,
    'Formation': 0,      'Guerilla': 0,     'Interception': 0,  'Leadership': 0,  'March': 0,    'Medic': 0,  'Mobility': 0,
    'Morale': 0,         'Navigation': 0,   'Pinch': 0,         'Range': 0,       'Sentry': 0,   'Shock': 0,  'Tactics': 0,
    'Woodsman': 0
  };

  // VALUES FROM XML FILE
  this.unitName = "";
  this.combat = "";
  this.bFirstStrikeImmune = 0;
  this.bNoDefensiveBonus = 0;
  this.bIgnoreBuildingDefense = 0;
  this.bNukeImmune = 0;
  this.iCost = 0;
  this.iCombat = 0;
  this.iAirCombat = 0;
  this.iFirstStrikes = 0;
  this.iChanceFirstStrikes = 0;
  this.iInterceptionProbability = 0;
  this.iEvasionProbability = 0;
  this.iWithdrawalProb = 0;
  this.iCollateralDamage = 0;
  this.iCollateralDamageLimit = 0;
  this.iCollateralDamageMaxUnits = 0;
  this.iCityAttack = 0;
  this.iCityDefense = 0;
  this.iAnimalCombat = 0;
  this.iHillsAttack = 0;
  this.iHillsDefense = 0;
  this.unitCombatMods = {};

  this.setPromotion = function(promo, setting) {
    this.promotions[promo] = setting;
  };
  
  this.removePromotion = function(promo) {
    this.promotions[promo] = 0;
  };
  
  this.clearPromotions = function() {
    for (var i = 0; i < this.promotions.length; i++) {
      this.promotions[i] = 0;
    }
  }
  
  this.setHP = function(hpValue) {
    this.hp = hpValue;
  };
  
  this.setUnitValues = function(unitTemplate) {
    switch (unitTemplate) {
      case "Lion":
        this.unitName = "Lion";
        this.unitClass = "LION";
        this.combat = "Animal";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = -1;
        this.iCombat = 2;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {};
        this.promotions = {};
        break;
      case "Bear":
        this.unitName = "Bear";
        this.unitClass = "BEAR";
        this.combat = "Animal";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = -1;
        this.iCombat = 3;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {};
        this.promotions = {};
        break;
      case "Panther":
        this.unitName = "Panther";
        this.unitClass = "PANTHER";
        this.combat = "Animal";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = -1;
        this.iCombat = 2;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {};
        this.promotions = {};
        break;
      case "Wolf":
        this.unitName = "Wolf";
        this.unitClass = "WOLF";
        this.combat = "Animal";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = -1;
        this.iCombat = 1;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {};
        this.promotions = {};
        break;
      case "Settler":
        this.unitName = "Settler";
        this.unitClass = "SETTLER";
        this.combat = "None";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = 100;
        this.iCombat = 0;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {};
        this.promotions = {};
        break;
      case "Worker":
        this.unitName = "Worker";
        this.unitClass = "WORKER";
        this.combat = "None"
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 1;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = 60;
        this.iCombat = 0;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {};
        this.promotions = {};
        break;
      case "Scout":
        this.unitName = "Scout";
        this.unitClass = "SCOUT";
        this.combat = "Recon";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = 15;
        this.iCombat = 1;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 100;
        this.iHillsAttack =
        this.iHillsDefense =
        this.unitCombatMods = {'AnimalCombat' : 100};
        this.promotions = {};
        break;
      case "Explorer":
        this.unitName = "Explorer";
        this.unitClass = "EXPLORER";
        this.combat = "Recon";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = 40;
        this.iCombat = 4;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {};
        this.promotions = {'Guerilla': 1, 'Woodsman': 1};
        break;
      case "Warrior":
        this.unitName = "Warrior";
        this.unitClass = "WARRIOR";
        this.combat = "MELEE";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = 15;
        this.iCombat = 2;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 25;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {'CityDefense': 25};
        this.promotions = {};
        break;
      case "Quechua":
        this.unitName = "Quechua";
        this.unitClass = "WARRIOR";
        this.combat = "MELEE";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = 15;
        this.iCombat = 2;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 25;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {'RANGED': 100};
        this.promotions = {'Combat': 1};
        break;
      case "Swordsman":
        this.unitName = "Swordsman";
        this.unitClass = "SWORDSMAN";
        this.combat = "MELEE";
        this.domain = "LAND";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = 40;
        this.iCombat = 6;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 10;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {};
        this.promotions = {};
        break;
      case "Jaguar":
        this.unitName = "Jaguar";
        this.unitClass = "SWORDSMAN";
        this.combat = "MELEE";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = 35;
        this.iCombat = 5;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 10;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {};
        this.promotions = {'Woodsman': 1};
        break;
      case "Gallic Warrior":
        this.unitName = "Gallic Warrior";
        this.unitClass = "SWORDSMAN";
        this.combat = "MELEE";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = 40;
        this.iCombat = 6;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 10;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {};
        this.promotions = {'Guerilla': 1};
        break;
      case "Praetorian":
        this.unitName = "Praetorian";
        this.unitClass = "SWORDSMAN";
        this.combat = "MELEE";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = 45;
        this.iCombat = 8;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {};
        this.promotions = {};
        break;
      case "Axeman":
        this.unitName = "Axeman";
        this.unitClass = "AXEMAN";
        this.combat = "MELEE";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = 35;
        this.iCombat = 5;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {'MELEE': 50};
        this.promotions = {};
        break;
      case "Phalanx":
        this.unitName = "Phalanx";
        this.unitClass = "AXEMAN";
        this.combat = "MELEE";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = 35;
        this.iCombat = 5;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {'CHARIOT': 100, 'MELEE': 50};
        this.promotions = {};
        break;
      case "Vulture":
        this.unitName = "Vulture";
        this.unitClass = "AXEMAN";
        this.combat = "MELEE";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = 35;
        this.iCombat = 6;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {'MELEE': 25};
        this.promotions = {};
        break;
      case "Dog Soldier":
        this.unitName = "Dog Soldier";
        this.unitClass = "AXEMAN";
        this.combat = "MELEE";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = 35;
        this.iCombat = 4;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits =
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {'MELEE': 100};
        this.promotions = {};
        break;
      case "Maceman":
        this.unitName = "Maceman";
        this.unitClass = "MACEMAN";
        this.combat = "MELEE";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = 70;
        this.iCombat = 8;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {'MELEE': 50};
        this.promotions = {};
        break;
      case "Samurai":
        this.unitName = "Samurai";
        this.unitClass = "MACEMAN";
        this.combat = "MELEE";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = 70;
        this.iCombat = 8;
        this.iAirCombat = 0;
        this.iFirstStrikes = 2;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {'MELEE': 50};
        this.promotions = {'Drill': 1};
        break;
      case "Berserker":
        this.unitName = "Berserker";
        this.unitClass = "MACEMAN";
        this.combat = "MELEE";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = 70;
        this.iCombat = 8;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0; 
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 10;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {'MELEE': 50}; 
        this.promotions = {'Amphibious': 1};
        break;
      case "Spearman":
        this.unitName = "Spearman";
        this.unitClass = "SPEARMAN";
        this.combat = "MELEE";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = 35;
        this.iCombat = 4;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {'MOUNTED': 100};
        this.promotions = {};
        break;
      case "Impi":
        this.unitName = "Impi";
        this.unitClass = "SPEARMAN";
        this.combat = "MELEE";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = 35;
        this.iCombat = 4;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {'MOUNTED': 100};
        this.promotions = {'Mobility': 1};
        break;
      case "Holkan":
        this.unitName = "Holkan";
        this.unitClass = "SPEARMAN";
        this.combat = "MELEE";
        this.bFirstStrikeImmune = 1;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = 35;
        this.iCombat = 4;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {'MOUNTED': 100};
        this.promotions = {};
        break;
      case "Pikeman":
        this.unitName = "Pikeman";
        this.unitClass = "PIKEMAN";
        this.combat = "MELEE";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = 60;
        this.iCombat = 6;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {'MOUNTED': 100};
        this.promotions = {};
        break;
      case "Landsknecht":
        this.unitName = "Landsknecht";
        this.unitClass = "PIEKMAN";
        this.combat = "MELEE";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = 60;
        this.iCombat = 6;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {'MELEE': 100, 'MOUNTED': 100};
        this.promotions = {};
        break;
      case "Musketman":
        this.unitName = "Musketman";
        this.unitClass = "MUSKETMAN";
        this.combat = "GUNPOWDER";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.iCost = 80;
        this.iCombat = 9;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {};
        this.promotions = {};
        break;
      case "Musketeer":
        this.unitName = "Musketeer";
        this.unitClass = "MUSKETMAN";
        this.combat = "GUNPOWDER";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.iCost = 80;
        this.iCombat = 9;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {};
        this.promotions = {};
        break;
      case "Janissary":
        this.unitName = "Janissary";
        this.unitClass = "MUSKETMAN";
        this.combat = "GUNPOWDER";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.iCost = 80;
        this.iCombat = 9;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {'MELEE': 25, 'RANGED': 25, 'MOUNTED': 25};
        this.promotions = {};
        break;
      case "Oromo Warrior":
        this.unitName = "Oromo Warrior";
        this.unitClass = "MUSKETMAN";
        this.combat = "GUNPOWDER";
        this.bFirstStrikeImmune = 1;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.iCost = 80;
        this.iCombat = 9;
        this.iAirCombat = 0;
        this.iFirstStrikes = 1;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {};
        this.promotions = {'Drill': 2};
        break;
      case "Rifleman":
        this.unitName = "Rifleman";
        this.unitClass = "RIFLEMAN";
        this.combat = "GUNPOWDER";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.iCost = 110;
        this.iCombat = 14;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {'MOUNTED': 25};
        this.promotions = {};
        break;
      case "Redcoat":
        this.unitName = "Redcoat";
        this.unitClass = "RIFLEMAN";
        this.combat = "GUNPOWDER";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.iCost = 110;
        this.iCombat = 14;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {'GUNPOWDER': 25, 'MOUNTED': 25};
        this.promotions = {};
        break;
      case "Grenadier":
        this.unitName = "Grenadier";
        this.unitClass = "GRENADIER";
        this.combat = "GUNPOWDER";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.iCost = 100;
        this.iCombat = 12;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {'RIFLEMAN': 50};
        this.promotions = {};
        break;
      case "Anti-Tank Infantry":
        this.unitName = "Anti-Tank Infantry"
        this.unitClass = "AT_INFANTRY";
        this.combat = "GUNPOWDER";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.iCost = 120;
        this.iCombat = 14;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 20;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {'ARMOR': 100};
        this.promotions = {'Ambush': 1};
        break;
      case "Infantry":
        this.unitName = "Infantry";
        this.unitClass = "INFANTRY";
        this.combat = "GUNPOWDER";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.iCost = 140;
        this.iCombat = 20;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {'GUNPOWDER': 25};
        this.promotions = {};
        break;
      case "SAM Infantry":
        this.unitName = "SAM Infantry"
        this.unitClass = "SAM_INFANTRY";
        this.combat = "GUNPOWDER";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.iCost = 150;
        this.iCombat = 18;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 40;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {'HELICOPTER': 75};
        this.promotions = {};
        break;
      case "Mobile SAM":
        this.unitName = "Mobile SAM";
        this.unitClass = "MOBILE_SAM";
        this.combat = "GUNPOWDER";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.iCost = 220;
        this.iCombat = 22;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 50;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {'HELICOPTER':50};
        this.promotions = {};
        break;
      case "Marine":
        this.unitName = "MARINE";
        this.unitClass = "RIFLEMAN";
        this.combat = "GUNPOWDER";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.iCost = 160;
        this.iCombat = 24;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {'MACHINE_GUN': 50, 'ARTILLERY': 50};
        this.promotions = {'Amphibious': 1};
        break;
      case "Navy Seal":
        this.unitName = "Navy Seal"
        this.unitClass = "MARINE";
        this.combat = "GUNPOWDER";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.iCost = 160;
        this.iCombat = 24;
        this.iAirCombat = 0;
        this.iFirstStrikes = 1;
        this.iChanceFirstStrikes = 1;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {'MACHINE_GUN': 50, 'ARTILLERY': 50};
        this.promotions = {'Amphibious': 1, 'March': 1};
        break;
      case "Paratrooper":
        this.unitName = "Paratrooper";
        this.unitClass = "PARATROOPER";
        this.combat = "GUNPOWDER";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.iCost = 160;
        this.iCombat = 24;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 25;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {};
        this.promotions = {};
        break;
      case "Mechanized Infantry":
        this.unitName = "Mechanized Infantry":
        this.unitClass = "MECHANIZED_INFANTRY";
        this.combat = "GUNPOWDER";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 1;
        this.bNukeImmune = 0;
        this.iCost = 200;
        this.iCombat = 32;
        this.iAirCombat = 0;
        this.iFirstStrikes = 0;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 20;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {};
        this.promotions = {'March': 1};
        break;
      case "Archer":
        this.unitName = "Archer";
        this.unitClass = "ARCHER";
        this.combat = "RANGED";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus =0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = 25;
        this.iCombat = 3;
        this.iAirCombat = 0;
        this.iFirstStrikes = 1;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 50;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 25;
        this.unitCombatMods = {};
        this.promotions = {};
        break;
      case "Skirmisher":
        this.unitName = "Skirmisher";
        this.unitClass = "ARCHER";
        this.combat = "RANGED";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = 25;
        this.iCombat = 4;
        this.iAirCombat = 0;
        this.iFirstStrikes = 1;
        this.iChanceFirstStrikes = 1;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 50;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 25;
        this.unitCombatMods = {};
        this.promotions = {};
        break;
      case "Bowman":
        this.unitName = "Bowman";
        this.unitClass = "ARCHER";
        this.combat = "RANGED";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = 25;
        this.iCombat = 3;
        this.iAirCombat = 0;
        this.iFirstStrikes = 1;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 50;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 25;
        this.unitCombatMods = {'MELEE': 50};
        this.promotions = {};
        break;
      case "Longbowman":
        this.unitName = "Longbowman";
        this.unitClass = "LONGBOWMAN";
        this.combat = "RANGED";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = 50;
        this.iCombat = 6;
        this.iAirCombat = 0;
        this.iFirstStrikes = 1;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 25;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 25;
        this.unitCombatMods = {};
        this.promotions = {};
        break;
      case "Crossbowman":
        this.unitName = "Crossbowman";
        this.unitClass = "CROSSBOWMAN";
        this.combat = "RANGED";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = 60;
        this.iCombat = 6;
        this.iAirCombat = 0;
        this.iFirstStrikes = 1;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 0;
        this.iCollateralDamageLimit = 0;
        this.iCollateralDamageMaxUnits = 0;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {'MELEE': 50};
        this.promotions = {};
        break;
      case "Cho-Ko-Nu":
        this.unitName = "Cho-Ko-Nu"
        this.unitClass = "CROSSBOWMAN";
        this.combat = "RANGED";
        this.bFirstStrikeImmune = 0;
        this.bNoDefensiveBonus = 0;
        this.bIgnoreBuildingDefense = 0;
        this.bNukeImmune = 0;
        this.iCost = 60;
        this.iCombat = 6;
        this.iAirCombat = 0;
        this.iFirstStrikes = 2;
        this.iChanceFirstStrikes = 0;
        this.iInterceptionProbability = 0;
        this.iEvasionProbability = 0;
        this.iWithdrawalProb = 0;
        this.iCollateralDamage = 50;
        this.iCollateralDamageLimit = 60;
        this.iCollateralDamageMaxUnits = 5;
        this.iCityAttack = 0;
        this.iCityDefense = 0;
        this.iAnimalCombat = 0;
        this.iHillsAttack = 0;
        this.iHillsDefense = 0;
        this.unitCombatMods = {'MELEE': 50};
        this.promotions = {};
        break;
      case "Chariot":
        this.unitName = "Chariot";
        this.unitClass = "CHARIOT";
        this.combat = "MOUNTED";
        this.bFirstStrikeImmune =
        this.bNoDefensiveBonus =
        this.bIgnoreBuildingDefense =
        this.bNukeImmune =
        this.iCost =
        this.iCombat =
        this.iAirCombat =
        this.iFirstStrikes =
        this.iChanceFirstStrikes =
        this.iInterceptionProbability =
        this.iEvasionProbability =
        this.iWithdrawalProb =
        this.iCollateralDamage =
        this.iCollateralDamageLimit =
        this.iCollateralDamageMaxUnits =
        this.iCityAttack =
        this.iCityDefense =
        this.iAnimalCombat =
        this.iHillsAttack =
        this.iHillsDefense =
        this.unitCombatMods =
        this.promotions =
        break;
      case "War Chariot":
        this.unitName =
        this.combat =
        this.bFirstStrikeImmune =
        this.bNoDefensiveBonus =
        this.bIgnoreBuildingDefense =
        this.bNukeImmune =
        this.iCost =
        this.iCombat =
        this.iAirCombat =
        this.iFirstStrikes =
        this.iChanceFirstStrikes =
        this.iInterceptionProbability =
        this.iEvasionProbability =
        this.iWithdrawalProb =
        this.iCollateralDamage =
        this.iCollateralDamageLimit =
        this.iCollateralDamageMaxUnits =
        this.iCityAttack =
        this.iCityDefense =
        this.iAnimalCombat =
        this.iHillsAttack =
        this.iHillsDefense =
        this.unitCombatMods =
        this.promotions =
        break;
      case "Immortal":
        this.unitName =
        this.combat =
        this.bFirstStrikeImmune =
        this.bNoDefensiveBonus =
        this.bIgnoreBuildingDefense =
        this.bNukeImmune =
        this.iCost =
        this.iCombat =
        this.iAirCombat =
        this.iFirstStrikes =
        this.iChanceFirstStrikes =
        this.iInterceptionProbability =
        this.iEvasionProbability =
        this.iWithdrawalProb =
        this.iCollateralDamage =
        this.iCollateralDamageLimit =
        this.iCollateralDamageMaxUnits =
        this.iCityAttack =
        this.iCityDefense =
        this.iAnimalCombat =
        this.iHillsAttack =
        this.iHillsDefense =
        this.unitCombatMods =
        this.promotions =
        break;
      case "Horse Archer":
        this.unitName =
        this.combat =
        this.bFirstStrikeImmune =
        this.bNoDefensiveBonus =
        this.bIgnoreBuildingDefense =
        this.bNukeImmune =
        this.iCost =
        this.iCombat =
        this.iAirCombat =
        this.iFirstStrikes =
        this.iChanceFirstStrikes =
        this.iInterceptionProbability =
        this.iEvasionProbability =
        this.iWithdrawalProb =
        this.iCollateralDamage =
        this.iCollateralDamageLimit =
        this.iCollateralDamageMaxUnits =
        this.iCityAttack =
        this.iCityDefense =
        this.iAnimalCombat =
        this.iHillsAttack =
        this.iHillsDefense =
        this.unitCombatMods =
        this.promotions =
        break;
      case "Numidian Mercenary":
        this.unitName =
        this.combat =
        this.bFirstStrikeImmune =
        this.bNoDefensiveBonus =
        this.bIgnoreBuildingDefense =
        this.bNukeImmune =
        this.iCost =
        this.iCombat =
        this.iAirCombat =
        this.iFirstStrikes =
        this.iChanceFirstStrikes =
        this.iInterceptionProbability =
        this.iEvasionProbability =
        this.iWithdrawalProb =
        this.iCollateralDamage =
        this.iCollateralDamageLimit =
        this.iCollateralDamageMaxUnits =
        this.iCityAttack =
        this.iCityDefense =
        this.iAnimalCombat =
        this.iHillsAttack =
        this.iHillsDefense =
        this.unitCombatMods =
        this.promotions =
        break;
      case "Keshik":
        this.unitName =
        this.combat =
        this.bFirstStrikeImmune =
        this.bNoDefensiveBonus =
        this.bIgnoreBuildingDefense =
        this.bNukeImmune =
        this.iCost =
        this.iCombat =
        this.iAirCombat =
        this.iFirstStrikes =
        this.iChanceFirstStrikes =
        this.iInterceptionProbability =
        this.iEvasionProbability =
        this.iWithdrawalProb =
        this.iCollateralDamage =
        this.iCollateralDamageLimit =
        this.iCollateralDamageMaxUnits =
        this.iCityAttack =
        this.iCityDefense =
        this.iAnimalCombat =
        this.iHillsAttack =
        this.iHillsDefense =
        this.unitCombatMods =
        this.promotions =
        break;
      case "Knight":
        this.unitName =
        this.combat =
        this.bFirstStrikeImmune =
        this.bNoDefensiveBonus =
        this.bIgnoreBuildingDefense =
        this.bNukeImmune =
        this.iCost =
        this.iCombat =
        this.iAirCombat =
        this.iFirstStrikes =
        this.iChanceFirstStrikes =
        this.iInterceptionProbability =
        this.iEvasionProbability =
        this.iWithdrawalProb =
        this.iCollateralDamage =
        this.iCollateralDamageLimit =
        this.iCollateralDamageMaxUnits =
        this.iCityAttack =
        this.iCityDefense =
        this.iAnimalCombat =
        this.iHillsAttack =
        this.iHillsDefense =
        this.unitCombatMods =
        this.promotions =
        break;
      case "Camel Archer":
        this.unitName =
        this.combat =
        this.bFirstStrikeImmune =
        this.bNoDefensiveBonus =
        this.bIgnoreBuildingDefense =
        this.bNukeImmune =
        this.iCost =
        this.iCombat =
        this.iAirCombat =
        this.iFirstStrikes =
        this.iChanceFirstStrikes =
        this.iInterceptionProbability =
        this.iEvasionProbability =
        this.iWithdrawalProb =
        this.iCollateralDamage =
        this.iCollateralDamageLimit =
        this.iCollateralDamageMaxUnits =
        this.iCityAttack =
        this.iCityDefense =
        this.iAnimalCombat =
        this.iHillsAttack =
        this.iHillsDefense =
        this.unitCombatMods =
        this.promotions =
        break;
      case "Cataphract":
        this.unitName =
        this.combat =
        this.bFirstStrikeImmune =
        this.bNoDefensiveBonus =
        this.bIgnoreBuildingDefense =
        this.bNukeImmune =
        this.iCost =
        this.iCombat =
        this.iAirCombat =
        this.iFirstStrikes =
        this.iChanceFirstStrikes =
        this.iInterceptionProbability =
        this.iEvasionProbability =
        this.iWithdrawalProb =
        this.iCollateralDamage =
        this.iCollateralDamageLimit =
        this.iCollateralDamageMaxUnits =
        this.iCityAttack =
        this.iCityDefense =
        this.iAnimalCombat =
        this.iHillsAttack =
        this.iHillsDefense =
        this.unitCombatMods =
        this.promotions =
        break;
      case "Conquistador":
        this.unitName =
        this.combat =
        this.bFirstStrikeImmune =
        this.bNoDefensiveBonus =
        this.bIgnoreBuildingDefense =
        this.bNukeImmune =
        this.iCost =
        this.iCombat =
        this.iAirCombat =
        this.iFirstStrikes =
        this.iChanceFirstStrikes =
        this.iInterceptionProbability =
        this.iEvasionProbability =
        this.iWithdrawalProb =
        this.iCollateralDamage =
        this.iCollateralDamageLimit =
        this.iCollateralDamageMaxUnits =
        this.iCityAttack =
        this.iCityDefense =
        this.iAnimalCombat =
        this.iHillsAttack =
        this.iHillsDefense =
        this.unitCombatMods =
        this.promotions =
        break;
      case "Cuirassier":
        this.unitName =
        this.combat =
        this.bFirstStrikeImmune =
        this.bNoDefensiveBonus =
        this.bIgnoreBuildingDefense =
        this.bNukeImmune =
        this.iCost =
        this.iCombat =
        this.iAirCombat =
        this.iFirstStrikes =
        this.iChanceFirstStrikes =
        this.iInterceptionProbability =
        this.iEvasionProbability =
        this.iWithdrawalProb =
        this.iCollateralDamage =
        this.iCollateralDamageLimit =
        this.iCollateralDamageMaxUnits =
        this.iCityAttack =
        this.iCityDefense =
        this.iAnimalCombat =
        this.iHillsAttack =
        this.iHillsDefense =
        this.unitCombatMods =
        this.promotions =
        break;
      case "Cavalry":
        this.unitName =
        this.combat =
        this.bFirstStrikeImmune =
        this.bNoDefensiveBonus =
        this.bIgnoreBuildingDefense =
        this.bNukeImmune =
        this.iCost =
        this.iCombat =
        this.iAirCombat =
        this.iFirstStrikes =
        this.iChanceFirstStrikes =
        this.iInterceptionProbability =
        this.iEvasionProbability =
        this.iWithdrawalProb =
        this.iCollateralDamage =
        this.iCollateralDamageLimit =
        this.iCollateralDamageMaxUnits =
        this.iCityAttack =
        this.iCityDefense =
        this.iAnimalCombat =
        this.iHillsAttack =
        this.iHillsDefense =
        this.unitCombatMods =
        this.promotions =
        break;
      case "Cossack":
        this.unitName =
        this.combat =
        this.bFirstStrikeImmune =
        this.bNoDefensiveBonus =
        this.bIgnoreBuildingDefense =
        this.bNukeImmune =
        this.iCost =
        this.iCombat =
        this.iAirCombat =
        this.iFirstStrikes =
        this.iChanceFirstStrikes =
        this.iInterceptionProbability =
        this.iEvasionProbability =
        this.iWithdrawalProb =
        this.iCollateralDamage =
        this.iCollateralDamageLimit =
        this.iCollateralDamageMaxUnits =
        this.iCityAttack =
        this.iCityDefense =
        this.iAnimalCombat =
        this.iHillsAttack =
        this.iHillsDefense =
        this.unitCombatMods =
        this.promotions =
        break;
      case "War Elephant":
        this.unitName =
        this.combat =
        this.bFirstStrikeImmune =
        this.bNoDefensiveBonus =
        this.bIgnoreBuildingDefense =
        this.bNukeImmune =
        this.iCost =
        this.iCombat =
        this.iAirCombat =
        this.iFirstStrikes =
        this.iChanceFirstStrikes =
        this.iInterceptionProbability =
        this.iEvasionProbability =
        this.iWithdrawalProb =
        this.iCollateralDamage =
        this.iCollateralDamageLimit =
        this.iCollateralDamageMaxUnits =
        this.iCityAttack =
        this.iCityDefense =
        this.iAnimalCombat =
        this.iHillsAttack =
        this.iHillsDefense =
        this.unitCombatMods =
        this.promotions =
        break;
      case "Ballista Elephant":
        this.unitName =
        this.combat =
        this.bFirstStrikeImmune =
        this.bNoDefensiveBonus =
        this.bIgnoreBuildingDefense =
        this.bNukeImmune =
        this.iCost =
        this.iCombat =
        this.iAirCombat =
        this.iFirstStrikes =
        this.iChanceFirstStrikes =
        this.iInterceptionProbability =
        this.iEvasionProbability =
        this.iWithdrawalProb =
        this.iCollateralDamage =
        this.iCollateralDamageLimit =
        this.iCollateralDamageMaxUnits =
        this.iCityAttack =
        this.iCityDefense =
        this.iAnimalCombat =
        this.iHillsAttack =
        this.iHillsDefense =
        this.unitCombatMods =
        this.promotions =
        break;
      case "Tank":
        this.unitName =
        this.combat =
        this.bFirstStrikeImmune =
        this.bNoDefensiveBonus =
        this.bIgnoreBuildingDefense =
        this.bNukeImmune =
        this.iCost =
        this.iCombat =
        this.iAirCombat =
        this.iFirstStrikes =
        this.iChanceFirstStrikes =
        this.iInterceptionProbability =
        this.iEvasionProbability =
        this.iWithdrawalProb =
        this.iCollateralDamage =
        this.iCollateralDamageLimit =
        this.iCollateralDamageMaxUnits =
        this.iCityAttack =
        this.iCityDefense =
        this.iAnimalCombat =
        this.iHillsAttack =
        this.iHillsDefense =
        this.unitCombatMods =
        this.promotions =
        break;
      case "Panzer":
        this.unitName =
        this.combat =
        this.bFirstStrikeImmune =
        this.bNoDefensiveBonus =
        this.bIgnoreBuildingDefense =
        this.bNukeImmune =
        this.iCost =
        this.iCombat =
        this.iAirCombat =
        this.iFirstStrikes =
        this.iChanceFirstStrikes =
        this.iInterceptionProbability =
        this.iEvasionProbability =
        this.iWithdrawalProb =
        this.iCollateralDamage =
        this.iCollateralDamageLimit =
        this.iCollateralDamageMaxUnits =
        this.iCityAttack =
        this.iCityDefense =
        this.iAnimalCombat =
        this.iHillsAttack =
        this.iHillsDefense =
        this.unitCombatMods =
        this.promotions =
        break;
      case "Modern Armor":
        this.unitName =
        this.combat =
        this.bFirstStrikeImmune =
        this.bNoDefensiveBonus =
        this.bIgnoreBuildingDefense =
        this.bNukeImmune =
        this.iCost =
        this.iCombat =
        this.iAirCombat =
        this.iFirstStrikes =
        this.iChanceFirstStrikes =
        this.iInterceptionProbability =
        this.iEvasionProbability =
        this.iWithdrawalProb =
        this.iCollateralDamage =
        this.iCollateralDamageLimit =
        this.iCollateralDamageMaxUnits =
        this.iCityAttack =
        this.iCityDefense =
        this.iAnimalCombat =
        this.iHillsAttack =
        this.iHillsDefense =
        this.unitCombatMods =
        this.promotions =
        break;

    }
  
  };
  
  
}
